from selenium.webdriver import Chrome
from time import sleep

driver = Chrome(executable_path="../../drivers/chromedriver.exe")
driver.get("https://demowebshop.tricentis.com/")
sleep(3)
driver.maximize_window()
sleep(3)
link = driver.find_element("link text", "Register")
sleep(3)
link.click()
sleep(2)
gender = driver.find_element("id","gender-female")
gender.click()
sleep(2)
fname = driver.find_element("id","FirstName")
fname.send_keys("Test")
sleep(2)
lname = driver.find_element("id","LastName")
lname.send_keys("User1")
sleep(2)
email = driver.find_element("id", "Email")
email.send_keys("testuser1@maildrop.cc")
sleep(2)
pwd = driver.find_element("id","Password")
pwd.send_keys("123456")
sleep(2)
cpwd = driver.find_element("id", "ConfirmPassword")
cpwd.send_keys("123456")
sleep(2)
btn = driver.find_element("id", "register-button")
btn.click()
sleep(5)
driver.close()


